# Generated by Django 5.2.5 on 2025-09-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pii_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piidetectionrecord',
            name='entity_assessments',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
