FROM node:18

WORKDIR /app

# 先复制 package.json 和 lock 文件（npm/yarn/pnpm 需要）
COPY frontend/package*.json ./

# 安装依赖（缓存依赖层）
RUN npm install --verbose

# 再复制前端源码
COPY frontend/ /app/

# 开发环境配置
ENV HOST 0.0.0.0
ENV PORT 8080
ENV CHOKIDAR_USEPOLLING=true

CMD ["npm", "run", "dev"]
