version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - presidio-analyzer
    env_file:
      - backend/.env
    restart: always

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app  # 假设前端代码在 frontend 目录下
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # 让Vite或Vue CLI监听文件更稳定
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: compliance_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  presidio-analyzer:
    image: mcr.microsoft.com/presidio-analyzer
    ports:
      - "3000:3000"
    environment:
      - PRESIDIO_DEFAULT_LANGUAGE=zh
      - ENABLE_TRACE_LOGS=1
    command: >
      /bin/bash -c "
      pip install flask requests spacy yaml&&
      python -m spacy download zh_core_web_sm &&
      python -m spacy download zh_core_web_trf &&
      python app.py --host 0.0.0.0 --log-level DEBUG"
    restart: always

volumes:
  postgres_data:
